In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("Mall_Customers.csv")

In [3]:
dataset.head()

CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [4]:
dataset.isnull().any()

CustomerID                False
Genre                     False
Age                       False
Annual Income (k$)        False
Spending Score (1-100)    False
dtype: bool

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["Genre"]=le.fit_transform(dataset["Genre"])

In [6]:
dataset.head()

CustomerID  Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1      1   19                  15                      39
1           2      1   21                  15                      81
2           3      0   20                  16                       6
3           4      0   23                  16                      77
4           5      0   31                  17                      40

In [7]:
x=dataset.iloc[:,0:4].values
y=dataset.iloc[:,4].values


In [8]:
x

array([[  1,   1,  19,  15],
       [  2,   1,  21,  15],
       [  3,   0,  20,  16],
       [  4,   0,  23,  16],
       [  5,   0,  31,  17],
       [  6,   0,  22,  17],
       [  7,   0,  35,  18],
       [  8,   0,  23,  18],
       [  9,   1,  64,  19],
       [ 10,   0,  30,  19],
       [ 11,   1,  67,  19],
       [ 12,   0,  35,  19],
       [ 13,   0,  58,  20],
       [ 14,   0,  24,  20],
       [ 15,   1,  37,  20],
       [ 16,   1,  22,  20],
       [ 17,   0,  35,  21],
       [ 18,   1,  20,  21],
       [ 19,   1,  52,  23],
       [ 20,   0,  35,  23],
       [ 21,   1,  35,  24],
       [ 22,   1,  25,  24],
       [ 23,   0,  46,  25],
       [ 24,   1,  31,  25],
       [ 25,   0,  54,  28],
       [ 26,   1,  29,  28],
       [ 27,   0,  45,  28],
       [ 28,   1,  35,  28],
       [ 29,   0,  40,  29],
       [ 30,   0,  23,  29],
       [ 31,   1,  60,  30],
       [ 32,   0,  21,  30],
       [ 33,   1,  53,  33],
       [ 34,   1,  18,  33],
       [ 35,  

In [9]:
y

array([39, 81,  6, 77, 40, 76,  6, 94,  3, 72, 14, 99, 15, 77, 13, 79, 35,
       66, 29, 98, 35, 73,  5, 73, 14, 82, 32, 61, 31, 87,  4, 73,  4, 92,
       14, 81, 17, 73, 26, 75, 35, 92, 36, 61, 28, 65, 55, 47, 42, 42, 52,
       60, 54, 60, 45, 41, 50, 46, 51, 46, 56, 55, 52, 59, 51, 59, 50, 48,
       59, 47, 55, 42, 49, 56, 47, 54, 53, 48, 52, 42, 51, 55, 41, 44, 57,
       46, 58, 55, 60, 46, 55, 41, 49, 40, 42, 52, 47, 50, 42, 49, 41, 48,
       59, 55, 56, 42, 50, 46, 43, 48, 52, 54, 42, 46, 48, 50, 43, 59, 43,
       57, 56, 40, 58, 91, 29, 77, 35, 95, 11, 75,  9, 75, 34, 71,  5, 88,
        7, 73, 10, 72,  5, 93, 40, 87, 12, 97, 36, 74, 22, 90, 17, 88, 20,
       76, 16, 89,  1, 78,  1, 73, 35, 83,  5, 93, 26, 75, 20, 95, 27, 63,
       13, 75, 10, 92, 13, 86, 15, 69, 14, 90, 32, 86, 15, 88, 39, 97, 24,
       68, 17, 85, 23, 69,  8, 91, 16, 79, 28, 74, 18, 83], dtype=int64)

In [10]:
x.shape

(200, 4)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler 
sc =StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [13]:
x_train

array([[ 6.14101752e-01,  1.16316000e+00, -1.31358807e+00,
         4.71130603e-01],
       [-5.79436487e-01, -8.59726954e-01,  3.07472996e-01,
        -4.80648393e-01],
       [-1.28151780e+00, -8.59726954e-01,  4.48434827e-01,
        -1.24207159e+00],
       [ 2.45509061e-01,  1.16316000e+00, -1.38406899e+00,
         1.28490165e-01],
       [ 1.21087087e+00, -8.59726954e-01, -1.85893416e-01,
         1.00412684e+00],
       [-6.32092586e-01, -8.59726954e-01,  1.08276307e+00,
        -5.18719553e-01],
       [-1.59745440e+00,  1.16316000e+00,  1.78757223e+00,
        -1.58471203e+00],
       [-4.21468191e-01,  1.16316000e+00, -8.90702575e-01,
        -2.52221434e-01],
       [ 3.33269225e-01, -8.59726954e-01,  8.71320323e-01,
         2.42703644e-01],
       [ 7.72070049e-01, -8.59726954e-01, -4.67817079e-01,
         5.85344083e-01],
       [-4.91676323e-01, -8.59726954e-01,  5.89396659e-01,
        -4.42577234e-01],
       [ 4.38581423e-01, -8.59726954e-01, -1.10214532e+00,
      

In [14]:
x.shape

(200, 4)

In [15]:
dataset.head()

CustomerID  Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1      1   19                  15                      39
1           2      1   21                  15                      81
2           3      0   20                  16                       6
3           4      0   23                  16                      77
4           5      0   31                  17                      40

In [16]:
from tensorflow.keras.models import Sequential #-used to initialize the model.
from tensorflow.keras.layers import Dense #- used to add layers of ANN


In [17]:
con=Sequential()

In [18]:
con.add(Dense(4,kernel_initializer="random_uniform",activation='relu'))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [19]:
con.add(Dense(8,kernel_initializer="random_uniform",activation='relu'))

In [20]:
con.add(Dense(1,kernel_initializer="random_uniform",activation='relu'))

In [21]:
con.compile("adam","mean_squared_error", metrics=['mse'])

In [22]:
con.fit(x_train,y_train,batch_size=32,epochs=10)

Epoch 1/10
160/160 [==============================] - 0s 803us/sample - loss: 3103.4248 - mean_squared_error: 3103.4248
Epoch 2/10
160/160 [==============================] - 0s 62us/sample - loss: 3102.9000 - mean_squared_error: 3102.9001
Epoch 3/10
160/160 [==============================] - 0s 41us/sample - loss: 3102.3370 - mean_squared_error: 3102.3369
Epoch 4/10
160/160 [==============================] - 0s 75us/sample - loss: 3101.7643 - mean_squared_error: 3101.7642
Epoch 5/10
160/160 [==============================] - 0s 57us/sample - loss: 3101.1615 - mean_squared_error: 3101.1616
Epoch 6/10
160/160 [==============================] - 0s 38us/sample - loss: 3100.5244 - mean_squared_error: 3100.5247
Epoch 7/10
160/160 [==============================] - 0s 64us/sample - loss: 3099.8438 - mean_squared_error: 3099.8435
Epoch 8/10
160/160 [==============================] - 0s 67us/sample - loss: 3099.1293 - mean_squared_error: 3099.1294
Epoch 9/10
160/160 [===========================

In [23]:
ypred=con.predict(x_test)

In [24]:
ypred

array([[0.0653314 ],
       [0.07125418],
       [0.0672522 ],
       [0.06601312],
       [0.07158211],
       [0.07340042],
       [0.06305469],
       [0.06939493],
       [0.06546881],
       [0.06998922],
       [0.06257599],
       [0.06744286],
       [0.07385197],
       [0.07015818],
       [0.06674798],
       [0.06308299],
       [0.06251508],
       [0.06798132],
       [0.06303347],
       [0.06706291],
       [0.07404256],
       [0.06854442],
       [0.06306249],
       [0.07016984],
       [0.06879756],
       [0.06680331],
       [0.07244992],
       [0.07350001],
       [0.06726364],
       [0.06427378],
       [0.06379843],
       [0.06460224],
       [0.06926925],
       [0.06689396],
       [0.06440952],
       [0.07509321],
       [0.06719639],
       [0.06369212],
       [0.06487294],
       [0.06831186]], dtype=float32)

In [25]:
y_test

array([29, 13, 46, 42, 69, 15, 76, 36, 15, 20, 55, 77, 32, 16, 51, 94, 92,
        9, 73, 47, 88, 97, 65, 73, 56, 91, 90, 97, 58, 28, 35, 41, 17, 54,
        5, 85, 75, 40, 44, 50], dtype=int64)

In [26]:
dataset.head()

CustomerID  Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1      1   19                  15                      39
1           2      1   21                  15                      81
2           3      0   20                  16                       6
3           4      0   23                  16                      77
4           5      0   31                  17                      40

In [27]:
yp=con.predict(sc.transform([[2,1,21,15]]))

In [28]:
yp

array([[0.06348212]], dtype=float32)